"""notifications table — inbox rows generated by @mentions & workflow events."""
from __future__ import annotations

import enum
import uuid
from datetime import datetime

from sqlalchemy import DateTime, Enum as SAEnum, ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.models._mixins import created_at_col, uuid_pk


class NotificationSource(str, enum.Enum):
    COMMENT_MENTION = "comment_mention"
    REVIEW_ASSIGNED = "review_assigned"
    REVIEW_STATUS_CHANGED = "review_status_changed"
    SURVEY_REQUESTED = "survey_requested"


class Notification(Base):
    __tablename__ = "notifications"

    id: Mapped[uuid.UUID] = uuid_pk()

    # Recipient of the notification.
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # User whose action generated it (may be null for system events).
    actor_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    source: Mapped[NotificationSource] = mapped_column(
        SAEnum(NotificationSource, name="notification_source", native_enum=False, length=48),
        nullable=False,
    )
    source_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True, index=True)
    feature_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("features.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )

    message: Mapped[str] = mapped_column(String(1024), nullable=False)

    read_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = created_at_col()

    recipient = relationship("User", foreign_keys=[user_id], lazy="joined")
    actor = relationship("User", foreign_keys=[actor_id], lazy="joined")
