worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream ollama_servers {
        least_conn;
        server 192.168.10.81:11434;
        server 192.168.10.67:11434;
        server 192.168.10.42:11434;
    }

    server {
        listen 11434;

        location / {
            proxy_pass http://ollama_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
        }
    }
}
